sudo: enabled

services:
- docker

script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t lyoko17220/osrps-standalone .

after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker push lyoko17220/osrps-standalone;
  fi